# Generated by Django 5.0.7 on 2024-08-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testeo_app', '0002_alter_inmueble_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='usuarios',
            field=models.ManyToManyField(related_name='inmuebles', to='testeo_app.usuario'),
        ),
    ]
